### ISSUE TITLE
Does this include videos of panels/presentations?

### ISSUE THREAD

**Issue by mat7ias** [ethberlin-hackathon/Talks-presentations#5]
For anyone who couldn't watch parts of the livestream due to timezone differences, will the presentation/panel videos be here? I believe files larger than 100 MB can be uploaded using git large file storage https://git-lfs.github.com/ so that might be needed.

**Comment by jspence425** [comment]
I believe they _will_ be uploaded here at some point.

**Comment by mat7ias** [comment]
Thanks @jspence425
